apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv0001
   labels:
      type: local
spec:
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteOnce
   storageClassName: manual
   hostPath:
         path: "/tmp/data01"